# Generated by Django 2.0.3 on 2018-08-16 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='文章')),
                ('pic', models.ImageField(upload_to='img', verbose_name='图片')),
                ('time', models.DateField(auto_now_add=True, verbose_name='添加时间')),
            ],
        ),
    ]
