# Generated by Django 2.0.3 on 2018-08-16 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='tittle',
            field=models.CharField(default='', max_length=50, verbose_name='标题'),
        ),
    ]
